### ISSUE TITLE
是否支持基于高版本如cm7.10.1版本  和 doris-1.2.4及以上版本的parcel包生成？

### ISSUE THREAD

**Issue by phoenixhadoop** [wangmiao1002/doris-cm#1]
是否支持基于高版本如cm7.10.1版本  和 doris-1.2.4及以上版本的parcel包生成？

**Comment by wangmiao1002** [comment]
理论上是支持的cm7的，这边没有环境没有测试；1.2.4版本可基于这个编译即可

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年09月08日 22:56 |
| 收件人 | wangmiao1002/doris-cm ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [wangmiao1002/doris-cm] 是否支持基于高版本如cm7.10.1版本 和 doris-1.2.4及以上版本的parcel包生成？ (Issue #1) |

是否支持基于高版本如cm7.10.1版本 和 doris-1.2.4及以上版本的parcel包生成？
